import { NextResponse } from 'next/server';
import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { currentUser } from '@/lib/current-user';
import { randomUUID } from 'crypto';
import { inventoryKey, normalizeCategory, normalizeProductName } from '@/lib/categories';
const schema=z.object({name:z.string().min(1),sku:z.string().optional(),category:z.string().trim().min(1,'Informe uma categoria.'),quantity:z.number().int().min(0).default(0),minStock:z.number().int().min(3,'O estoque mínimo deve ser pelo menos 3.'),unit:z.string().min(1).default('un')});
async function getUser(){return currentUser()}
export async function GET(req:Request){const u=await getUser();if(!u)return NextResponse.json({ok:false,message:'Não autenticado'},{status:401});const search=new URL(req.url).searchParams,q=search.get('q')||'',archived=search.get('archived')==='true';if(archived&&u.role!=='ADMIN')return NextResponse.json({ok:false,message:'Acesso restrito ao administrador.'},{status:403});const data=await prisma.product.findMany({where:{active:!archived,OR:[{name:{contains:q,mode:'insensitive'}},{sku:{contains:q,mode:'insensitive'}},{category:{contains:q,mode:'insensitive'}}]},orderBy:{name:'asc'}});return NextResponse.json({ok:true,data});}
export async function POST(req:Request){const u=await getUser();if(!u)return NextResponse.json({ok:false,message:'Não autenticado'},{status:401});if(u.role==='VIEWER')return NextResponse.json({ok:false,message:'Seu perfil permite apenas consultas.'},{status:403});try{const b=schema.parse(await req.json());const normalizedCategory=normalizeCategory(b.category),normalizedName=normalizeProductName(b.name);const categoryMatch=await prisma.product.findFirst({where:{category:{equals:normalizedCategory,mode:'insensitive'}},select:{category:true}});const category=categoryMatch?.category||normalizedCategory;const result=await prisma.$transaction(async(tx)=>{const candidates=await tx.product.findMany({where:{category:{equals:category,mode:'insensitive'}}});const existing=candidates.find(product=>inventoryKey(product.name)===inventoryKey(normalizedName));if(existing){if(!existing.active)throw new Error('Este equipamento já existe nos arquivados. Restaure-o antes de registrar um novo lote.');if(existing.unit.toLocaleLowerCase('pt-BR')!==b.unit.trim().toLocaleLowerCase('pt-BR'))throw new Error(`Este equipamento já usa a unidade “${existing.unit}”. Registre o lote com a mesma unidade.`);const product=b.quantity>0?await tx.product.update({where:{id:existing.id},data:{quantity:{increment:b.quantity}}}):existing;if(b.quantity>0)await tx.movement.create({data:{type:'IN',quantity:b.quantity,note:'Entrada de novo lote pelo cadastro',productId:existing.id,userId:u.id}});return{product,consolidated:true};}const data={...b,name:normalizedName,category,unit:b.unit.trim(),sku:b.sku?.trim()||`EQ-${randomUUID().slice(0,8).toUpperCase()}`};const product=await tx.product.create({data});if(b.quantity>0)await tx.movement.create({data:{type:'IN',quantity:b.quantity,note:'Estoque inicial',productId:product.id,userId:u.id}});return{product,consolidated:false};},{isolationLevel:'Serializable'});return NextResponse.json({ok:true,data:result.product,consolidated:result.consolidated},{status:result.consolidated?200:201});}catch(e:any){console.error('[products] Falha ao cadastrar:',e);const safeMessage=e?.issues?.[0]?.message||(e?.message?.startsWith('Este equipamento')?e.message:null)||'Confira os dados do equipamento.';return NextResponse.json({ok:false,message:safeMessage},{status:400});}}
