'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';

type Role = 'ADMIN' | 'OPERATOR' | 'VIEWER';
type Tab = 'products' | 'register' | 'categories' | 'movement' | 'history' | 'users' | 'settings';
type Product = { id:string;name:string;sku:string;category:string|null;quantity:number;minStock:number;unit:string;active?:boolean };
type Movement = { id:string;type:'IN'|'OUT';quantity:number;note:string|null;createdAt:string;product:Product;user:{name:string;registration:string};reversed?:boolean;isReversal?:boolean };
type CurrentUser = { id:string;name:string;registration:string;role:Role };
type ManagedUser = CurrentUser & { email:string|null;active:boolean;mustChangePassword:boolean };

const roleLabel:Record<Role,string>={ADMIN:'Administrador',OPERATOR:'Operador',VIEWER:'Consulta'};

export default function Dashboard(){
  const [tab,setTab]=useState<Tab>('products');
  const [current,setCurrent]=useState<CurrentUser|null>(null);
  const [products,setProducts]=useState<Product[]>([]);
  const [archivedProducts,setArchivedProducts]=useState<Product[]>([]);
  const [showArchived,setShowArchived]=useState(false);
  const [editingProduct,setEditingProduct]=useState<Product|null>(null);
  const [movements,setMovements]=useState<Movement[]>([]);
  const [users,setUsers]=useState<ManagedUser[]>([]);
  const [query,setQuery]=useState('');
  const [debouncedQuery,setDebouncedQuery]=useState('');
  const [historyQuery,setHistoryQuery]=useState('');
  const [historyType,setHistoryType]=useState('');
  const [historyPage,setHistoryPage]=useState(1);
  const [historyPages,setHistoryPages]=useState(1);
  const [historyTotal,setHistoryTotal]=useState(0);
  const [feedback,setFeedback]=useState<{kind:'ok'|'error';text:string}|null>(null);
  const [busy,setBusy]=useState(false);
  const [productForm,setProductForm]=useState({name:'',sku:'',category:'',quantity:0,minStock:3,unit:'un'});
  const [newCategory,setNewCategory]=useState('');
  const [movementForm,setMovementForm]=useState({productId:'',type:'IN' as 'IN'|'OUT',quantity:1,note:''});
  const [confirmingMovement,setConfirmingMovement]=useState(false);
  const [userForm,setUserForm]=useState({name:'',registration:'',email:'',role:'OPERATOR' as Role,password:''});
  const [retention,setRetention]=useState({years:1,count:0,password:'',confirmation:''});

  const load=useCallback(async()=>{
    try{
      const meResponse=await fetch('/api/auth/me');
      if(meResponse.status===401){window.location.href='/login';return;}
      const meData=await meResponse.json();setCurrent(meData.user);
      const params=new URLSearchParams({page:String(historyPage)});
      if(historyType)params.set('type',historyType);if(historyQuery)params.set('q',historyQuery);
      const [productResponse,movementResponse]=await Promise.all([fetch(`/api/products?q=${encodeURIComponent(debouncedQuery)}`),fetch(`/api/movements?${params}`)]);
      const [productData,movementData]=await Promise.all([productResponse.json(),movementResponse.json()]);
      if(!productResponse.ok)throw new Error(productData.message);if(!movementResponse.ok)throw new Error(movementData.message);
      setProducts(productData.data||[]);setMovements(movementData.data||[]);setHistoryPages(movementData.pagination?.pages||1);setHistoryTotal(movementData.pagination?.total||0);
      if(meData.user.role==='ADMIN'){const [usersResponse,archivedResponse]=await Promise.all([fetch('/api/users'),fetch(`/api/products?archived=true&q=${encodeURIComponent(debouncedQuery)}`)]);const [usersData,archivedData]=await Promise.all([usersResponse.json(),archivedResponse.json()]);if(usersResponse.ok)setUsers(usersData.data||[]);if(archivedResponse.ok)setArchivedProducts(archivedData.data||[]);}
    }catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível carregar os dados.'});}
  },[debouncedQuery,historyPage,historyQuery,historyType]);

  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const timer=setTimeout(()=>setDebouncedQuery(query),350);return()=>clearTimeout(timer);},[query]);

  const totals=useMemo(()=>({units:products.reduce((sum,p)=>sum+p.quantity,0),low:products.filter(p=>p.quantity<=p.minStock).length}),[products]);
  const categories=useMemo(()=>Object.entries(products.reduce<Record<string,Product[]>>((groups,product)=>{const category=product.category?.trim()||'Sem categoria';(groups[category]??=[]).push(product);return groups;},{})).sort(([a],[b])=>a.localeCompare(b,'pt-BR')),[products]);
  const categoryOptions=useMemo(()=>categories.map(([name])=>name).filter(name=>name!=='Sem categoria'),[categories]);
  const selectedMovementProduct=products.find(product=>product.id===movementForm.productId);
  const canEdit=current?.role!=='VIEWER';

  async function submitProduct(event:FormEvent){event.preventDefault();setBusy(true);try{const editing=Boolean(editingProduct),category=productForm.category==='__new'?newCategory:productForm.category;if(!category.trim())throw new Error('Selecione ou informe uma categoria.');const response=await fetch(editingProduct?`/api/products/${editingProduct.id}`:'/api/products',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{name:productForm.name,category,minStock:productForm.minStock,unit:productForm.unit}:{name:productForm.name,category,quantity:productForm.quantity,minStock:productForm.minStock,unit:productForm.unit})});const data=await response.json();if(!response.ok)throw new Error(data.message);cancelEdit();setFeedback({kind:'ok',text:editing?'Equipamento atualizado com sucesso.':data.consolidated?'Lote somado ao equipamento que já estava cadastrado.':'Equipamento cadastrado com sucesso.'});setTab('products');await load();}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível salvar.'});}finally{setBusy(false);}}
  function submitMovement(event:FormEvent){event.preventDefault();if(!selectedMovementProduct){setFeedback({kind:'error',text:'Selecione um equipamento.'});return;}if(movementForm.type==='OUT'&&movementForm.quantity>selectedMovementProduct.quantity){setFeedback({kind:'error',text:'A quantidade de saída é maior que o saldo disponível.'});return;}setConfirmingMovement(true);}
  async function confirmMovement(){setBusy(true);try{const response=await fetch('/api/movements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(movementForm)});const data=await response.json();if(!response.ok)throw new Error(data.message);setConfirmingMovement(false);setMovementForm({...movementForm,quantity:1,note:''});setFeedback({kind:'ok',text:movementForm.type==='IN'?'Entrada registrada.':'Saída registrada.'});setHistoryPage(1);await load();}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível movimentar.'});}finally{setBusy(false);}}
  async function reverseMovement(movement:Movement){if(!window.confirm(`Estornar esta ${movement.type==='IN'?'entrada':'saída'} de ${movement.quantity} unidade(s) de “${movement.product.name}”?`))return;setBusy(true);try{const response=await fetch(`/api/movements/${movement.id}/reverse`,{method:'POST'}),data=await response.json();if(!response.ok)throw new Error(data.message);setFeedback({kind:'ok',text:'Movimentação estornada. O registro original foi preservado.'});await load();}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível estornar.'});}finally{setBusy(false);}}
  async function submitUser(event:FormEvent){event.preventDefault();setBusy(true);try{const response=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(userForm)});const data=await response.json();if(!response.ok)throw new Error(data.message);setUserForm({name:'',registration:'',email:'',role:'OPERATOR',password:''});setFeedback({kind:'ok',text:'Usuário criado. Entregue a matrícula e a senha provisória.'});await load();}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível criar o usuário.'});}finally{setBusy(false);}}
  async function updateUser(id:string,change:{active?:boolean;role?:Role;password?:string}){setBusy(true);try{const response=await fetch(`/api/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(change)});const data=await response.json();if(!response.ok)throw new Error(data.message);setFeedback({kind:'ok',text:change.password?'Senha provisória atualizada.':'Usuário atualizado.'});await load();}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível atualizar.'});}finally{setBusy(false);}}
  function resetUserPassword(user:ManagedUser){const password=window.prompt(`Nova senha provisória para ${user.name} (mínimo 8 caracteres):`);if(password)void updateUser(user.id,{password});}
  function editProduct(product:Product){setEditingProduct(product);setNewCategory('');setProductForm({name:product.name,sku:product.sku,category:product.category||'',quantity:product.quantity,minStock:Math.max(3,product.minStock),unit:product.unit});setShowArchived(false);setTab('register');window.scrollTo({top:0,behavior:'smooth'});}
  function cancelEdit(){setEditingProduct(null);setNewCategory('');setProductForm({name:'',sku:'',category:'',quantity:0,minStock:3,unit:'un'});}
  async function archiveProduct(product:Product){if(!window.confirm(`Arquivar “${product.name}”? O histórico será preservado.`))return;setBusy(true);try{const response=await fetch(`/api/products/${product.id}`,{method:'DELETE'}),data=await response.json();if(!response.ok)throw new Error(data.message);setFeedback({kind:'ok',text:'Equipamento arquivado.'});await load();}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível arquivar.'});}finally{setBusy(false);}}
  async function restoreProduct(product:Product){setBusy(true);try{const response=await fetch(`/api/products/${product.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:true})}),data=await response.json();if(!response.ok)throw new Error(data.message);setFeedback({kind:'ok',text:'Equipamento restaurado ao estoque.'});await load();}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível restaurar.'});}finally{setBusy(false);}}
  async function previewRetention(years:number){setBusy(true);try{const response=await fetch(`/api/maintenance/history?years=${years}`),data=await response.json();if(!response.ok)throw new Error(data.message);setRetention({years,count:data.data.count,password:'',confirmation:''});}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível consultar o histórico.'});}finally{setBusy(false);}}
  async function deleteOldHistory(event:FormEvent){event.preventDefault();if(!window.confirm(`Apagar definitivamente ${retention.count} movimentação(ões) antiga(s)?`))return;setBusy(true);try{const response=await fetch('/api/maintenance/history',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify(retention)}),data=await response.json();if(!response.ok)throw new Error(data.message);setRetention({...retention,count:0,password:'',confirmation:''});setFeedback({kind:'ok',text:`${data.data.deleted} registro(s) antigo(s) foram apagados. Produtos e saldos foram preservados.`});setHistoryPage(1);await load();}catch(error){setFeedback({kind:'error',text:error instanceof Error?error.message:'Não foi possível limpar o histórico.'});}finally{setBusy(false);}}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});window.location.href='/login';}
  function navigate(next:Tab){setTab(next);setFeedback(null);if(next==='categories')setQuery('');if(next!=='products'&&next!=='register'){setShowArchived(false);cancelEdit();}window.scrollTo({top:0,behavior:'smooth'});}

  return <main className="app-shell">
    <header className="app-header"><div className="brand"><span className="logo">E</span><div><strong>Estoque</strong><small>Controle de equipamentos</small></div></div><div className="header-actions"><span className="user-chip">{current?.name} · {current?.registration}</span><button className="button ghost" onClick={logout}>Sair</button></div></header>
    <div className="workspace">
      <aside className="sidebar" aria-label="Navegação principal">
        <button className={tab==='products'?'active':''} onClick={()=>navigate('products')}><span>▦</span>Equipamentos</button>
        {canEdit?<button className={tab==='register'?'active':''} onClick={()=>{cancelEdit();navigate('register');}}><span>＋</span>Cadastrar</button>:null}
        <button className={tab==='categories'?'active':''} onClick={()=>navigate('categories')}><span>▤</span>Categorias</button>
        {canEdit?<button className={tab==='movement'?'active':''} onClick={()=>navigate('movement')}><span>⇄</span>Entrada e saída</button>:null}
        <button className={tab==='history'?'active':''} onClick={()=>navigate('history')}><span>◷</span>Histórico</button>
        {current?.role==='ADMIN'?<button className={tab==='users'?'active':''} onClick={()=>navigate('users')}><span>♙</span>Usuários</button>:null}
        {current?.role==='ADMIN'?<button className={tab==='settings'?'active':''} onClick={()=>{navigate('settings');void previewRetention(retention.years);}}><span>⚙</span>Manutenção</button>:null}
      </aside>
      <div className="content-area">
        {feedback?<div className={`feedback ${feedback.kind}`}>{feedback.text}<button onClick={()=>setFeedback(null)} aria-label="Fechar">×</button></div>:null}

        {tab==='products'?<>
          <section className="page-title"><div><p className="eyebrow">INVENTÁRIO</p><h1>{showArchived?'Equipamentos arquivados':'Equipamentos'}</h1><p>{showArchived?'Itens fora do estoque atual, com histórico preservado.':'Veja imediatamente o que existe e quanto está disponível.'}</p></div><div className="title-actions">{current?.role==='ADMIN'?<button className="button ghost" onClick={()=>{setShowArchived(v=>!v);cancelEdit();}}>{showArchived?'Ver estoque atual':'Ver arquivados'}</button>:null}{canEdit&&!showArchived?<button className="button primary" onClick={()=>navigate('register')}>+ Novo equipamento</button>:null}</div></section>
          <section className="stats"><article><span>Equipamentos</span><strong>{products.length}</strong></article><article><span>Unidades disponíveis</span><strong>{totals.units}</strong></article><article className={totals.low?'danger':''}><span>Estoque baixo</span><strong>{totals.low}</strong></article><article><span>Movimentações</span><strong>{historyTotal}</strong></article></section>
          <section className="panel"><div className="panel-heading search-heading"><div><h2>{showArchived?'Itens arquivados':'Estoque atual'}</h2></div><input className="search" placeholder="Pesquisar nome ou categoria" value={query} onChange={e=>setQuery(e.target.value)}/></div><ProductTable products={showArchived?archivedProducts:products} admin={current?.role==='ADMIN'} archived={showArchived} onEdit={editProduct} onArchive={archiveProduct} onRestore={restoreProduct}/></section>
        </>:null}

        {tab==='register'&&canEdit?<section className="page-section"><div className="page-title"><div><p className="eyebrow">CADASTRO</p><h1>{editingProduct?'Editar equipamento':'Cadastrar equipamento'}</h1><p>{editingProduct?'Corrija as informações sem alterar o histórico.':'Adicione um novo item ao estoque.'}</p></div></div><form className="panel compact-form" onSubmit={submitProduct}><label>Nome do equipamento<input placeholder="Ex.: Cabo HDMI" value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})} required/></label><label>Categoria<select value={productForm.category} onChange={e=>{setProductForm({...productForm,category:e.target.value});if(e.target.value!=='__new')setNewCategory('');}} required><option value="">Selecione uma categoria</option>{categoryOptions.map(category=><option value={category} key={category}>{category}</option>)}{current?.role==='ADMIN'?<option value="__new">+ Criar nova categoria</option>:null}</select></label>{productForm.category==='__new'?<label>Nome da nova categoria<input placeholder="Ex.: Cabos e adaptadores" value={newCategory} onChange={e=>setNewCategory(e.target.value)} required autoFocus/><small>O nome será padronizado automaticamente.</small></label>:null}<div className="field-grid three">{!editingProduct?<label>Quantidade inicial<input type="number" min="0" value={productForm.quantity} onChange={e=>setProductForm({...productForm,quantity:Number(e.target.value)})}/></label>:null}<label>Estoque mínimo<input type="number" min="3" value={productForm.minStock} onChange={e=>setProductForm({...productForm,minStock:Number(e.target.value)})} required/><small>Mínimo permitido: 3</small></label><label>Unidade<input value={productForm.unit} onChange={e=>setProductForm({...productForm,unit:e.target.value})} required/></label></div><div className="form-actions">{editingProduct?<button type="button" className="button ghost" onClick={()=>{cancelEdit();navigate('products');}}>Cancelar</button>:null}<button className="button primary" disabled={busy}>{editingProduct?'Salvar alterações':'Cadastrar equipamento'}</button></div></form></section>:null}

        {tab==='categories'?<section className="page-section"><div className="page-title"><div><p className="eyebrow">ORGANIZAÇÃO</p><h1>Categorias</h1><p>Veja os equipamentos agrupados pela categoria informada no cadastro.</p></div></div><div className="category-grid">{categories.length?categories.map(([category,items])=><section className="category-card" key={category}><div><h2>{category}</h2><span>{items.length} equipamento(s)</span></div><ul>{items.map(item=><li key={item.id}><strong>{item.name}</strong><span>{item.quantity} {item.unit}</span></li>)}</ul></section>):<div className="panel empty">Nenhuma categoria cadastrada.</div>}</div></section>:null}

        {tab==='movement'?<section className="page-section"><div className="page-title"><div><p className="eyebrow">MOVIMENTAÇÃO</p><h1>Entrada e saída</h1><p>Registre alterações no saldo do estoque.</p></div></div><form className="panel movement-card" onSubmit={submitMovement}><label>Equipamento<select value={movementForm.productId} onChange={e=>setMovementForm({...movementForm,productId:e.target.value})} required><option value="">Selecione</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {p.quantity} {p.unit}</option>)}</select></label><div className="field-grid"><label>Tipo<select value={movementForm.type} onChange={e=>setMovementForm({...movementForm,type:e.target.value as 'IN'|'OUT'})}><option value="IN">Entrada</option><option value="OUT">Saída</option></select></label><label>Quantidade<input type="number" min="1" value={movementForm.quantity} onChange={e=>setMovementForm({...movementForm,quantity:Number(e.target.value)})} required/></label></div><label>Observação<input placeholder="Motivo, destino ou responsável" value={movementForm.note} onChange={e=>setMovementForm({...movementForm,note:e.target.value})}/></label><button className={`button ${movementForm.type==='OUT'?'danger-button':'primary'}`} disabled={busy||!products.length}>Registrar {movementForm.type==='IN'?'entrada':'saída'}</button></form></section>:null}

        {tab==='history'?<section className="page-section"><div className="page-title"><div><p className="eyebrow">AUDITORIA</p><h1>Histórico de movimentações</h1><p>{historyTotal} registro(s), exibidos em páginas de até 25.</p></div></div><section className="panel"><div className="history-filters"><input placeholder="Equipamento, SKU ou responsável" value={historyQuery} onChange={e=>{setHistoryQuery(e.target.value);setHistoryPage(1);}}/><select value={historyType} onChange={e=>{setHistoryType(e.target.value);setHistoryPage(1);}}><option value="">Entradas e saídas</option><option value="IN">Somente entradas</option><option value="OUT">Somente saídas</option></select></div><MovementTable movements={movements} admin={current?.role==='ADMIN'} busy={busy} onReverse={reverseMovement}/><div className="pagination"><button className="button ghost" disabled={historyPage<=1} onClick={()=>setHistoryPage(p=>p-1)}>← Anterior</button><span>Página {historyPage} de {historyPages}</span><button className="button ghost" disabled={historyPage>=historyPages} onClick={()=>setHistoryPage(p=>p+1)}>Próxima →</button></div></section></section>:null}

        {tab==='users'&&current?.role==='ADMIN'?<section className="page-section"><div className="page-title"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Usuários e matrículas</h1><p>Controle quem pode consultar e movimentar o estoque.</p></div></div><section className="panel users-panel"><form className="user-form" onSubmit={submitUser}><label>Nome<input value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})} required/></label><label>Matrícula<input value={userForm.registration} onChange={e=>setUserForm({...userForm,registration:e.target.value.toUpperCase()})} required/></label><label>E-mail (opcional)<input type="email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></label><label>Perfil<select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value as Role})}><option value="OPERATOR">Operador</option><option value="VIEWER">Consulta</option><option value="ADMIN">Administrador</option></select></label><label>Senha provisória<input type="password" minLength={8} value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})} required/></label><button className="button primary" disabled={busy}>Criar usuário</button></form><div className="table-wrap"><table><thead><tr><th>Nome</th><th>Matrícula</th><th>Perfil</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><strong>{user.name}</strong><small className="cell-subtitle">{user.email||'Sem e-mail'}</small></td><td>{user.registration}</td><td><select className="compact-select" value={user.role} disabled={busy||user.id===current.id} onChange={e=>void updateUser(user.id,{role:e.target.value as Role})}><option value="ADMIN">Administrador</option><option value="OPERATOR">Operador</option><option value="VIEWER">Consulta</option></select></td><td><span className={`status ${user.active?'normal':'low'}`}>{user.active?(user.mustChangePassword?'Senha provisória':'Ativo'):'Bloqueado'}</span></td><td><div className="row-actions"><button className="button small ghost" onClick={()=>resetUserPassword(user)}>Nova senha</button><button className={`button small ${user.active?'danger-button':'primary'}`} disabled={user.id===current.id} onClick={()=>void updateUser(user.id,{active:!user.active})}>{user.active?'Bloquear':'Ativar'}</button></div></td></tr>)}</tbody></table></div></section></section>:null}

        {tab==='settings'&&current?.role==='ADMIN'?<section className="page-section"><div className="page-title"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Manutenção do histórico</h1><p>Remova somente movimentações antigas, sem alterar produtos, usuários ou saldos.</p></div></div><section className="panel maintenance-card"><div className="retention-options"><button className={`button ${retention.years===1?'primary':'ghost'}`} onClick={()=>void previewRetention(1)}>Mais de 1 ano</button><button className={`button ${retention.years===2?'primary':'ghost'}`} onClick={()=>void previewRetention(2)}>Mais de 2 anos</button></div><div className="maintenance-summary"><strong>{retention.count}</strong><span>movimentação(ões) podem ser removidas</span></div>{retention.count>0?<><a className="button ghost download-button" href={`/api/maintenance/history?years=${retention.years}&format=csv`}>Baixar backup CSV</a><form className="danger-zone" onSubmit={deleteOldHistory}><h2>Apagar histórico antigo</h2><p>Baixe o backup antes. Esta ação não pode ser desfeita.</p><label>Senha do administrador<input type="password" value={retention.password} onChange={e=>setRetention({...retention,password:e.target.value})} required/></label><label>Escreva APAGAR HISTORICO<input value={retention.confirmation} onChange={e=>setRetention({...retention,confirmation:e.target.value.toUpperCase()})} required/></label><button className="button danger-button" disabled={busy||retention.confirmation!=='APAGAR HISTORICO'}>Apagar {retention.count} registro(s)</button></form></>:<div className="notice safe-notice">Nenhuma movimentação ultrapassou o período escolhido. Nada será apagado.</div>}</section></section>:null}
      </div>
    </div>
    <footer className="site-footer">
      <span>© {new Date().getFullYear()} Sistema de Estoque</span>
      <span className="footer-divider" aria-hidden="true">•</span>
      <span>Desenvolvido por <a href="https://www.linkedin.com/in/samuel-ladeia" target="_blank" rel="noopener noreferrer">Samuel Ladeia</a></span>
      <span className="footer-divider" aria-hidden="true">•</span>
      <a href="/support" target="_blank" rel="noopener noreferrer" aria-label="Solicitar suporte e manutenção pelo WhatsApp de Samuel Ladeia">Suporte e manutenção</a>
    </footer>
    {confirmingMovement&&selectedMovementProduct?<div className="modal-backdrop" role="presentation" onMouseDown={()=>!busy&&setConfirmingMovement(false)}><section className="confirm-modal" role="dialog" aria-modal="true" aria-labelledby="confirm-movement-title" onMouseDown={event=>event.stopPropagation()}><span className={`confirmation-icon ${movementForm.type.toLowerCase()}`}>{movementForm.type==='IN'?'↓':'↑'}</span><h2 id="confirm-movement-title">Confirmar {movementForm.type==='IN'?'entrada':'saída'}</h2><p>Confira os dados antes de alterar o saldo.</p><dl><div><dt>Equipamento</dt><dd>{selectedMovementProduct.name}</dd></div><div><dt>Quantidade</dt><dd>{movementForm.quantity} {selectedMovementProduct.unit}</dd></div><div><dt>Saldo atual</dt><dd>{selectedMovementProduct.quantity} {selectedMovementProduct.unit}</dd></div><div><dt>Saldo após operação</dt><dd>{movementForm.type==='IN'?selectedMovementProduct.quantity+movementForm.quantity:selectedMovementProduct.quantity-movementForm.quantity} {selectedMovementProduct.unit}</dd></div>{movementForm.note?<div><dt>Observação</dt><dd>{movementForm.note}</dd></div>:null}</dl><div className="modal-actions"><button className="button ghost" disabled={busy} onClick={()=>setConfirmingMovement(false)}>Voltar e corrigir</button><button className={`button ${movementForm.type==='OUT'?'danger-button':'primary'}`} disabled={busy} onClick={()=>void confirmMovement()}>{busy?'Registrando...':'Confirmar movimentação'}</button></div></section></div>:null}
  </main>;
}

function ProductTable({products,admin,archived,onEdit,onArchive,onRestore}:{products:Product[];admin:boolean;archived:boolean;onEdit:(p:Product)=>void;onArchive:(p:Product)=>void;onRestore:(p:Product)=>void}){return <div className="table-wrap"><table><thead><tr><th>Nome</th><th>Categoria</th><th>Saldo</th><th>Mínimo</th><th>Status</th>{admin?<th>Ações</th>:null}</tr></thead><tbody>{products.length?products.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.category||'—'}</td><td>{p.quantity} {p.unit}</td><td>{p.minStock} {p.unit}</td><td><span className={`status ${archived||p.quantity<=p.minStock?'low':'normal'}`}>{archived?'Arquivado':p.quantity<=p.minStock?'Estoque baixo':'Normal'}</span></td>{admin?<td><div className="row-actions">{archived?<button className="button small primary" onClick={()=>onRestore(p)}>Restaurar</button>:<><button className="button small ghost" onClick={()=>onEdit(p)}>Editar</button><button className="button small danger-button" onClick={()=>onArchive(p)}>Arquivar</button></>}</div></td>:null}</tr>):<tr><td colSpan={admin?6:5} className="empty">Nenhum equipamento encontrado.</td></tr>}</tbody></table></div>}
function MovementTable({movements,admin,busy,onReverse}:{movements:Movement[];admin:boolean;busy:boolean;onReverse:(movement:Movement)=>void}){return <div className="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Equipamento</th><th>Quantidade</th><th>Responsável</th><th>Observação</th>{admin?<th>Ações</th>:null}</tr></thead><tbody>{movements.length?movements.map(m=><tr key={m.id} className={m.reversed?'reversed-row':''}><td>{new Date(m.createdAt).toLocaleString('pt-BR')}</td><td><span className={`movement ${m.type.toLowerCase()}`}>{m.isReversal?'Estorno':m.type==='IN'?'Entrada':'Saída'}</span></td><td>{m.product.name}</td><td>{m.quantity}</td><td>{m.user.name}<small className="cell-subtitle">{m.user.registration}</small></td><td>{m.reversed?'Movimentação estornada':m.note?.replace(/^ESTORNO:[^ ]+ — /,'')||'—'}</td>{admin?<td>{m.reversed?<span className="status low">Estornada</span>:m.isReversal?<span className="status normal">Correção</span>:<button className="button small ghost" disabled={busy} onClick={()=>onReverse(m)}>Estornar</button>}</td>:null}</tr>):<tr><td colSpan={admin?7:6} className="empty">Nenhuma movimentação encontrada.</td></tr>}</tbody></table></div>}
